### PR TITLE
Fix UI and delete features bug

### LINKED ISSUE #16: Note delete feature not work and buttons icon is not appropriate
**Describe the bug**
---
* delete feature not work, because of tag and tagmap
* button icon is not trash, it's book icon

### PR DESCRIPTION
**Pull request by detectiveCrow**
### Icons
* delete button icon update book to trash
### Feature
* fix delete features bug

Closes #16

### CODE REVIEW

File: src/app/Modules/NoteModule.php [hunk 1]
```diff
@@ -111,7 +112,15 @@ public function update(Request $request)
...
     DB::transaction(function () {
+      $tagMap = $this->note->tagMap();
+
+      foreach ($tagMap->get() as $row) {
+        $row->delete();
+      }
+
       $this->note->delete();
+
+      $tagMap->delete();
```
Comment (detectiveCrow) [inline src/app/Modules/NoteModule.php:123]: not necessary parts
delete feature is only to do delete tagmap and note

File: src/app/Models/TagMap.php [hunk 2]
```diff
@@ -23,4 +23,13 @@ class TagMap extends Model
...
   ];
+
+  /**
+   * @inheritdoc
+   * @return \Illuminate\Database\Eloquent\Relations\HasOne
+   */
+  public function tag()
+  {
+    return $this->hasOne(Tag::class);
+  }
```
Comment (detectiveCrow) [inline src/app/Models/TagMap.php:34]: not necessary parts also
